export interface Listing {
  id: string
  user_name: string
  user_profile_number: string
  user_address: string
  category: 'Food' | 'Education' | 'Cloth' | 'Others'
  title: string
  description: string
  quantity: number
  quality: 'New' | 'Good' | 'Used' | 'Poor'
  pickup_address: string
  contact_number: string
  listing_image_url: string
}

export const mockListings: Listing[] = [
  // Food Category
  {
    id: 'LIST-001',
    user_name: 'Sarah Johnson',
    user_profile_number: 'USR-001',
    user_address: '123 Main Street, New York, NY 10001',
    category: 'Food',
    title: 'Fresh Organic Vegetables',
    description: 'Fresh organic vegetables from my garden. Includes tomatoes, cucumbers, bell peppers, and fresh herbs. All harvested this week. Great for healthy cooking and meal prep.',
    quantity: 15,
    quality: 'New',
    pickup_address: '123 Main Street, New York, NY 10001, Apartment 4B',
    contact_number: '+1 (555) 123-4567',
    listing_image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=300&fit=crop',
  },
  {
    id: 'LIST-002',
    user_name: 'Michael Chen',
    user_profile_number: 'USR-002',
    user_address: '456 Oak Avenue, Los Angeles, CA 90001',
    category: 'Food',
    title: 'Homemade Baked Goods',
    description: 'Freshly baked bread, muffins, and cookies. Made with organic ingredients and no preservatives. Perfect for breakfast or snacks. Baking daily!',
    quantity: 25,
    quality: 'New',
    pickup_address: '456 Oak Avenue, Los Angeles, CA 90001, Unit 12',
    contact_number: '+1 (555) 234-5678',
    listing_image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop',
  },
  {
    id: 'LIST-003',
    user_name: 'Emma Rodriguez',
    user_profile_number: 'USR-003',
    user_address: '789 Pine Road, Chicago, IL 60601',
    category: 'Food',
    title: 'Canned Goods Collection',
    description: 'Various canned goods including beans, soups, and vegetables. All within expiration date. Great for emergency food supplies or everyday meals.',
    quantity: 40,
    quality: 'Good',
    pickup_address: '789 Pine Road, Chicago, IL 60601, First Floor',
    contact_number: '+1 (555) 345-6789',
    listing_image_url: 'https://images.unsplash.com/photo-1615367423055-94e5e95ac0b7?w=400&h=300&fit=crop',
  },
  {
    id: 'LIST-004',
    user_name: 'David Thompson',
    user_profile_number: 'USR-004',
    user_address: '321 Elm Street, Houston, TX 77001',
    category: 'Food',
    title: 'Fresh Fruits - Seasonal Selection',
    description: 'Seasonal fresh fruits including apples, oranges, bananas, and berries. Sourced from local farms. Healthy and delicious!',
    quantity: 30,
    quality: 'New',
    pickup_address: '321 Elm Street, Houston, TX 77001, Suite 5',
    contact_number: '+1 (555) 456-7890',
    listing_image_url: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=400&h=300&fit=crop',
  },
  
  // Education Category
  {
    id: 'LIST-005',
    user_name: 'Jessica Martinez',
    user_profile_number: 'USR-005',
    user_address: '654 Maple Drive, Phoenix, AZ 85001',
    category: 'Education',
    title: 'College Textbooks - Computer Science',
    description: 'Complete set of computer science textbooks including Data Structures, Algorithms, Database Systems, and Software Engineering. All in excellent condition with minimal highlights.',
    quantity: 8,
    quality: 'Good',
    pickup_address: '654 Maple Drive, Phoenix, AZ 85001, Apartment 302',
    contact_number: '+1 (555) 567-8901',
    listing_image_url: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=300&fit=crop',
  },
  {
    id: 'LIST-006',
    user_name: 'Robert Williams',
    user_profile_number: 'USR-006',
    user_address: '987 Cedar Lane, Philadelphia, PA 19101',
    category: 'Education',
    title: 'Children\'s Books Collection',
    description: 'Large collection of children\'s books including picture books, storybooks, and early reader books. Perfect for ages 3-10. Great condition!',
    quantity: 50,
    quality: 'Good',
    pickup_address: '987 Cedar Lane, Philadelphia, PA 19101, Unit 7',
    contact_number: '+1 (555) 678-9012',
    listing_image_url: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=300&fit=crop',
  },
  {
    id: 'LIST-007',
    user_name: 'Amanda Lee',
    user_profile_number: 'USR-007',
    user_address: '147 Birch Court, San Antonio, TX 78201',
    category: 'Education',
    title: 'Art Supplies - Painting & Drawing',
    description: 'Complete art supply set including paints, brushes, canvases, sketchbooks, and drawing pencils. Perfect for students or hobby artists.',
    quantity: 12,
    quality: 'Used',
    pickup_address: '147 Birch Court, San Antonio, TX 78201, Floor 2',
    contact_number: '+1 (555) 789-0123',
    listing_image_url: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400&h=300&fit=crop',
  },
  {
    id: 'LIST-008',
    user_name: 'Christopher Brown',
    user_profile_number: 'USR-008',
    user_address: '258 Spruce Street, San Diego, CA 92101',
    category: 'Education',
    title: 'Language Learning Materials',
    description: 'Spanish and French language learning books, CDs, and flashcards. Great for beginners or intermediate learners. Includes workbooks.',
    quantity: 20,
    quality: 'Good',
    pickup_address: '258 Spruce Street, San Diego, CA 92101, Apartment 15',
    contact_number: '+1 (555) 890-1234',
    listing_image_url: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400&h=300&fit=crop',
  },
  
  // Cloth Category
  {
    id: 'LIST-009',
    user_name: 'Michelle Garcia',
    user_profile_number: 'USR-009',
    user_address: '369 Willow Way, Dallas, TX 75201',
    category: 'Cloth',
    title: 'Baby Clothes - Size 0-12 Months',
    description: 'Gently used baby clothes in excellent condition. Includes onesies, pajamas, shirts, pants, and accessories. All cleaned and sanitized.',
    quantity: 35,
    quality: 'Good',
    pickup_address: '369 Willow Way, Dallas, TX 75201, House 22',
    contact_number: '+1 (555) 901-2345',
    listing_image_url: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=400&h=300&fit=crop',
  },
  {
    id: 'LIST-010',
    user_name: 'James Wilson',
    user_profile_number: 'USR-010',
    user_address: '741 Ash Avenue, San Jose, CA 95101',
    category: 'Cloth',
    title: 'Winter Jackets & Coats',
    description: 'Collection of winter jackets and coats in various sizes. Includes both men\'s and women\'s styles. All in good condition, ready for winter season.',
    quantity: 18,
    quality: 'Used',
    pickup_address: '741 Ash Avenue, San Jose, CA 95101, Unit 9',
    contact_number: '+1 (555) 012-3456',
    listing_image_url: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=400&h=300&fit=crop',
  },
  {
    id: 'LIST-011',
    user_name: 'Lisa Anderson',
    user_profile_number: 'USR-011',
    user_address: '852 Poplar Street, Austin, TX 78701',
    category: 'Cloth',
    title: 'Professional Work Attire',
    description: 'Business professional clothing including suits, blazers, dress shirts, and dress pants. Various sizes available. Perfect for job interviews or office work.',
    quantity: 22,
    quality: 'Good',
    pickup_address: '852 Poplar Street, Austin, TX 78701, Suite 3',
    contact_number: '+1 (555) 123-4567',
    listing_image_url: 'https://images.unsplash.com/photo-1594938291221-94f18cbb3c48?w=400&h=300&fit=crop',
  },
  {
    id: 'LIST-012',
    user_name: 'Daniel Moore',
    user_profile_number: 'USR-012',
    user_address: '963 Chestnut Road, Jacksonville, FL 32201',
    category: 'Cloth',
    title: 'Sportswear & Athletic Gear',
    description: 'Sports clothing and athletic gear including workout clothes, running shoes, yoga mats, and sports accessories. Good condition, ready to use.',
    quantity: 28,
    quality: 'Used',
    pickup_address: '963 Chestnut Road, Jacksonville, FL 32201, Building A',
    contact_number: '+1 (555) 234-5678',
    listing_image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
  },
  
  // Others Category
  {
    id: 'LIST-013',
    user_name: 'Jennifer Taylor',
    user_profile_number: 'USR-013',
    user_address: '159 Magnolia Drive, Fort Worth, TX 76101',
    category: 'Others',
    title: 'Household Items & Kitchenware',
    description: 'Assorted household items including kitchen utensils, dishes, pots, pans, and small appliances. All in working condition. Great for new homeowners.',
    quantity: 45,
    quality: 'Used',
    pickup_address: '159 Magnolia Drive, Fort Worth, TX 76101, Apartment 8',
    contact_number: '+1 (555) 345-6789',
    listing_image_url: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&h=300&fit=crop',
  },
  {
    id: 'LIST-014',
    user_name: 'Matthew White',
    user_profile_number: 'USR-014',
    user_address: '357 Dogwood Lane, Columbus, OH 43201',
    category: 'Others',
    title: 'Furniture - Tables & Chairs',
    description: 'Wooden dining table with 4 matching chairs. Slightly used but in good condition. Perfect for small apartments or starter homes. Dimensions: 6ft x 3ft table.',
    quantity: 5,
    quality: 'Used',
    pickup_address: '357 Dogwood Lane, Columbus, OH 43201, Unit 14',
    contact_number: '+1 (555) 456-7890',
    listing_image_url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=300&fit=crop',
  },
  {
    id: 'LIST-015',
    user_name: 'Nicole Harris',
    user_profile_number: 'USR-015',
    user_address: '741 Sycamore Street, Charlotte, NC 28201',
    category: 'Others',
    title: 'Toys & Games Collection',
    description: 'Collection of children\'s toys and board games in good condition. Includes action figures, puzzles, board games, and educational toys. Ages 3-12.',
    quantity: 60,
    quality: 'Used',
    pickup_address: '741 Sycamore Street, Charlotte, NC 28201, House 5',
    contact_number: '+1 (555) 567-8901',
    listing_image_url: 'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=400&h=300&fit=crop',
  },
  {
    id: 'LIST-016',
    user_name: 'Ryan Clark',
    user_profile_number: 'USR-016',
    user_address: '852 Hickory Avenue, Seattle, WA 98101',
    category: 'Others',
    title: 'Electronics - Small Appliances',
    description: 'Various small electronics including blenders, toasters, coffee makers, and lamps. All tested and in working condition. Great for college students or first apartment.',
    quantity: 15,
    quality: 'Good',
    pickup_address: '852 Hickory Avenue, Seattle, WA 98101, Suite 12',
    contact_number: '+1 (555) 678-9012',
    listing_image_url: 'https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=400&h=300&fit=crop',
  },
]

